### ISSUE TITLE
Need credit and cleanup for code from SourceSplit 

### ISSUE THREAD

**Issue by kilpatrq** [Traderain/Listdemo-#1]
listdemo.cs contains uncredited code from Fatalis's [SourceSplit](https://github.com/fatalis/SourceSplit), including lines that are specific to Portal.

**Comment by Traderain** [comment]
It's from CBeni's Source Engine Demo Tool: https://sourceruns.org/index.php?topic=995.0 but he might have copied it from there I don't know.

**Comment by a1193362693** [comment]
You can provide a binary file ？ 
I for some reason can not be compiled

**Comment by Traderain** [comment]
The compiled version is on the releases page. (If you want to modify it paste your errors at least)
